name: trvslhlt
favicon: null
layout_spectrum: 1
typography_spectrum: 0.83104
title: and other misspelled words
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b4ab8e'
    - '#41262b'
    - '#707571'
    - '#e5ebf7'
    - '#cf4943'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose:
  - name: follow
    item: 'null'
    url: null
