name: trvslhlt
favicon: null
layout_spectrum: 0.75516
typography_spectrum: 0.83104
title: trvslhlt
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#001300'
    - '#a9c5b6'
    - '#4a643f'
    - '#4c3348'
    - '#849583'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 1
purpose:
  - name: follow
    item: 'null'
    url: null
