name: trvslhlt
favicon: null
layout_spectrum: 0.52413
title: trvslhlt
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b8b8b0'
    - '#d8d4cb'
    - '#6d7275'
    - '#191c21'
    - '#57544f'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: 'null'
    url: null
